In [12]:
import os
import gc
import math

import pandas as pd
import numpy as np

import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor
from sklearn.linear_model import SGDRegressor, LinearRegression, Ridge
from sklearn.preprocessing import MinMaxScaler


from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.metrics import log_loss
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from tqdm import tqdm
import matplotlib.pyplot as plt
import time
import warnings
warnings.filterwarnings('ignore')

# 1 导入数据

In [13]:
path="./data/"
train_data=pd.read_csv(path+'train.csv')
test_data=pd.read_csv(path+'testA.csv')
print('Train data shape:',train_data.shape)
print('TestA data shape:',test_data.shape)

Train data shape: (100000, 3)
TestA data shape: (20000, 2)


In [14]:
#有10w训练集2w验证集，均只有两个特征
train_data.head().append(train_data.tail())

id                                  heartbeat_signals  label
0          0  0.9912297987616655,0.9435330436439665,0.764677...    0.0
1          1  0.9714822034884503,0.9289687459588268,0.572932...    0.0
2          2  1.0,0.9591487564065292,0.7013782792997189,0.23...    2.0
3          3  0.9757952826275774,0.9340884687738161,0.659636...    0.0
4          4  0.0,0.055816398940721094,0.26129357194994196,0...    2.0
99995  99995  1.0,0.677705342021188,0.22239242747868546,0.25...    0.0
99996  99996  0.9268571578157265,0.9063471198026871,0.636993...    2.0
99997  99997  0.9258351628306013,0.5873839035878395,0.633226...    3.0
99998  99998  1.0,0.9947621698382489,0.8297017704865509,0.45...    2.0
99999  99999  0.9259994004527861,0.916476635326053,0.4042900...    0.0

# 构建评分特征


In [5]:
def abs_sum(y_pre,y_tru):
    #y_pre为预测概率矩阵
    #y_tru为真实类别矩阵
    y_pre=np.array(y_pre)
    y_tru=np.array(y_tru)
    loss=sum(sum(abs(y_pre-y_tru)))
    return loss

# 2.数据预处理

In [30]:
def reduce_mem_usage(df):
    start_mem = df.memory_usage().sum() / 1024**2 #显示数据框所有的内存情况
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))#输出情况
    
    for col in df.columns:#循环每一列名：'id', 'heartbeat_signals', 'label'
        col_type = df[col].dtype #参考每一列的数据类型
        
        if col_type != object: #判断：如果列类型不是对象的话则取出该列的最大值和最小值，
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':#进一步判断是否为int属性
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:#这里为了将数值小的转化为int8，节省空间，以下均是依次依次分段找到最为合适最省空间的格式
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        else:
            df[col] = df[col].astype('category')

    end_mem = df.memory_usage().sum() / 1024**2 
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))
    
    return df

In [43]:
# 简单预处理
train_list = []#设置空列表

for items in train_data.values:
    train_list.append([items[0]] + [float(i) for i in items[1].split(',')] + [items[2]])#将ID以及心跳信号以及标签分布数字化



In [60]:
train = pd.DataFrame(np.array(train_list))#重新完成构建训练集
train.columns = ['id'] + ['s_'+str(i) for i in range(len(train_list[0])-2)] + ['label']#重新命名列名，其中将心跳信号名字以s开头进行命名
train = reduce_mem_usage(train)#节省空间


Memory usage of dataframe is 157.93 MB
Memory usage after optimization is: 39.67 MB
Decreased by 74.9%


# 对训练集同样处理，只是无标签

In [62]:
test_list=[]
for items in test_data.values:
    test_list.append([items[0]] + [float(i) for i in items[1].split(',')])

test = pd.DataFrame(np.array(test_list))
test.columns = ['id'] + ['s_'+str(i) for i in range(len(test_list[0])-1)]
test = reduce_mem_usage(test)

Memory usage of dataframe is 31.43 MB
Memory usage after optimization is: 7.90 MB
Decreased by 74.9%


# 查看简单预处理后的数据框

In [64]:
train.head()

id       s_0       s_1       s_2       s_3       s_4       s_5       s_6  \
0  0.0  0.991211  0.943359  0.764648  0.618652  0.379639  0.190796  0.040222   
1  1.0  0.971680  0.929199  0.572754  0.178467  0.122986  0.132324  0.094421   
2  2.0  1.000000  0.958984  0.701172  0.231812  0.000000  0.080688  0.128418   
3  3.0  0.975586  0.934082  0.659668  0.249878  0.237061  0.281494  0.249878   
4  4.0  0.000000  0.055817  0.261230  0.359863  0.433105  0.453613  0.499023   

        s_7       s_8  ...  s_196  s_197  s_198  s_199  s_200  s_201  s_202  \
0  0.026001  0.031708  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1  0.089600  0.030487  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2  0.187500  0.280762  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3  0.249878  0.241455  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4  0.542969  0.616699  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

   s_203  s_204  label  
0    0.0    0.0    0.0  
1    0.0    0.0    0.0  
2    0.0    0.0    2.0  
3    0.0    0.0    0.0  
4    0.0    0.0    2.0  

[5 rows x 207 columns]

In [65]:
test.head()

id       s_0       s_1       s_2       s_3       s_4       s_5  \
0  100000.0  0.991699  1.000000  0.631836  0.136230  0.041412  0.102722   
1  100001.0  0.607422  0.541504  0.340576  0.000000  0.090698  0.164917   
2  100002.0  0.975098  0.670898  0.686523  0.708496  0.718750  0.716797   
3  100003.0  0.995605  0.916992  0.520996  0.000000  0.221802  0.404053   
4  100004.0  1.000000  0.888184  0.745605  0.531738  0.380371  0.224609   

        s_6       s_7       s_8  ...     s_195     s_196     s_197     s_198  \
0  0.120850  0.123413  0.107910  ...  0.000000  0.000000  0.000000  0.000000   
1  0.195068  0.168823  0.198853  ...  0.389893  0.386963  0.367188  0.364014   
2  0.720703  0.701660  0.596680  ...  0.000000  0.000000  0.000000  0.000000   
3  0.490479  0.527344  0.518066  ...  0.000000  0.000000  0.000000  0.000000   
4  0.091125  0.057648  0.003914  ...  0.000000  0.000000  0.000000  0.000000   

      s_199     s_200     s_201     s_202     s_203    s_204  
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  
1  0.360596  0.357178  0.350586  0.350586  0.350586  0.36377  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  

[5 rows x 206 columns]

# 3 训练和测试数据准备

In [66]:
x_train = train.drop(['id','label'], axis=1)#去除掉id和因变量
y_train = train['label']#label作为因变量
x_test=test.drop(['id'], axis=1)

# 4训练模型

In [72]:
def cv_model(clf, train_x, train_y, test_x, clf_name):#规定交叉验证的通用baseline
    folds = 5     #5折交叉验证
    seed = 2021   #设置种子
    kf = KFold(n_splits=folds, shuffle=True, random_state=seed)  #根据N折划分数据
    test = np.zeros((test_x.shape[0],4))  #构建输出格式的0矩阵

    cv_scores = []
    onehot_encoder = OneHotEncoder(sparse=False)
    for i, (train_index, valid_index) in enumerate(kf.split(train_x, train_y)):
        print('************************************ {} ************************************'.format(str(i+1)))
        trn_x, trn_y, val_x, val_y = train_x.iloc[train_index], train_y[train_index], train_x.iloc[valid_index], train_y[valid_index]
        
        if clf_name == "lgb":
            train_matrix = clf.Dataset(trn_x, label=trn_y)
            valid_matrix = clf.Dataset(val_x, label=val_y)

            params = {
                'boosting_type': 'gbdt',
                'objective': 'multiclass',
                'num_class': 4,
                'num_leaves': 2 ** 5,
                'feature_fraction': 0.8,
                'bagging_fraction': 0.8,
                'bagging_freq': 4,
                'learning_rate': 0.1,
                'seed': seed,
                'nthread': 28,
                'n_jobs':24,
                'verbose': -1,
            }

            model = clf.train(params, 
                      train_set=train_matrix, 
                      valid_sets=valid_matrix, 
                      num_boost_round=2000, 
                      verbose_eval=100, 
                      early_stopping_rounds=200)
            val_pred = model.predict(val_x, num_iteration=model.best_iteration)
            test_pred = model.predict(test_x, num_iteration=model.best_iteration) 
            
        val_y=np.array(val_y).reshape(-1, 1)  #将列表转化为n行一列的矩阵，便于下一步转化为onehot
        val_y = onehot_encoder.fit_transform(val_y)
        print('预测的概率矩阵为：')
        print(test_pred)
        test += test_pred
        score=abs_sum(val_y, val_pred)
        cv_scores.append(score)
        print(cv_scores)
    print("%s_scotrainre_list:" % clf_name, cv_scores)
    print("%s_score_mean:" % clf_name, np.mean(cv_scores))
    print("%s_score_std:" % clf_name, np.std(cv_scores))
    test=test/kf.n_splits

    return test

In [73]:
def lgb_model(x_train, y_train, x_test):
    lgb_test = cv_model(lgb, x_train, y_train, x_test, "lgb")
    return lgb_test

In [74]:
lgb_test = lgb_model(x_train, y_train, x_test)

************************************ 1 ************************************
[LightGBM] [Warning] num_threads is set with nthread=28, will be overridden by n_jobs=24. Current value: num_threads=24
Training until validation scores don't improve for 200 rounds
[100]	valid_0's multi_logloss: 0.0525735
[200]	valid_0's multi_logloss: 0.0422444
[300]	valid_0's multi_logloss: 0.0407076
[400]	valid_0's multi_logloss: 0.0420398
Early stopping, best iteration is:
[289]	valid_0's multi_logloss: 0.0405457
预测的概率矩阵为：
[[9.99969791e-01 2.85197261e-05 1.00341946e-06 6.85357631e-07]
 [7.93287264e-05 7.69060914e-04 9.99151590e-01 2.00810971e-08]
 [5.75356884e-07 5.04051497e-08 3.15322414e-07 9.99999059e-01]
 ...
 [6.79267940e-02 4.30206297e-04 9.31640185e-01 2.81516302e-06]
 [9.99960477e-01 3.94098074e-05 8.34030725e-08 2.94638661e-08]
 [9.88705846e-01 2.14081630e-03 6.67418381e-03 2.47915423e-03]]
[607.0736049372185]
************************************ 2 ************************************
[LightGBM] [

In [75]:
lgb_test

array([[9.99981254e-01, 1.71125438e-05, 8.45046636e-07, 7.88733736e-07],
       [4.28215579e-05, 6.13652971e-04, 9.99343511e-01, 1.41575174e-08],
       [1.62884845e-06, 1.96662878e-07, 1.37365693e-06, 9.99996801e-01],
       ...,
       [4.11101448e-02, 3.43163508e-04, 9.58539745e-01, 6.94675406e-06],
       [9.99960370e-01, 3.94933168e-05, 8.45736848e-08, 5.23076338e-08],
       [9.58337628e-01, 7.65806626e-03, 3.06443728e-02, 3.35993298e-03]])

In [76]:
temp=pd.DataFrame(lgb_test)
temp

0             1             2             3
0      0.999981  1.711254e-05  8.450466e-07  7.887337e-07
1      0.000043  6.136530e-04  9.993435e-01  1.415752e-08
2      0.000002  1.966629e-07  1.373657e-06  9.999968e-01
3      0.999970  1.909713e-05  1.097002e-05  3.576703e-08
4      0.999983  1.769712e-06  1.482817e-05  1.966254e-07
...         ...           ...           ...           ...
19995  0.998096  3.060176e-04  1.085313e-04  1.489757e-03
19996  0.999846  1.436305e-04  1.074898e-05  8.837766e-08
19997  0.041110  3.431635e-04  9.585397e-01  6.946754e-06
19998  0.999960  3.949332e-05  8.457368e-08  5.230763e-08
19999  0.958338  7.658066e-03  3.064437e-02  3.359933e-03

[20000 rows x 4 columns]

In [78]:
result=pd.read_csv('./data/sample_submit.csv')
result['label_0']=temp[0]
result['label_1']=temp[1]
result['label_2']=temp[2]
result['label_3']=temp[3]
result.to_csv('submit.csv',index=False)